include: package:pedantic/analysis_options.1.11.0.yaml

analyzer: 
  strong-mode:
    implicit-casts: false 
    implicit-dynamic: false

Linter: 
  rules:
    # - prefer_const_constructors
    # - prefer_const_declarations
    # - avoid_print
    # - use_key_in_widget constructors
    - always_use_package_imports